FROM node:20-alpine AS builder
WORKDIR /app
COPY minierp/apps/admin/package*.json ./
RUN npm install
COPY minierp/apps/admin/ .
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
EXPOSE 3002
CMD ["node", "server.js"]
